name: berlin_transport
description: A simple Flutter app for the Berlin/Brandenburg public transport

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  http: any
  provider: any
  
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    path: /Users/mattsullivan/Development/src/flutter/official_github_repos/flutter_web/packages/flutter_web
  flutter_web_ui:
    path: /Users/mattsullivan/Development/src/flutter/official_github_repos/flutter_web/packages/flutter_web_ui
  provider:
    path: /Users/mattsullivan/Development/src/flutter/official_github_repos/provider

#flutter:
#  uses-material-design: true

#  assets:
    # Cached api results
#    - assets/location_origin.json
#    - assets/location_destination.json
#    - assets/journey.json

    # Animations
#    - assets/flare/bus.flr
#    - assets/flare/metro.flr
#    - assets/flare/train.flr


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
